In [1]:
import pandas as pd
import sys
sys.path.append('..')
from python.b_eda.exploracion_datos import *

In [2]:
df_ventas = pd.read_csv('../dataset/raw/ventas.csv')

In [3]:
# Primeras 5 filas
df_ventas.head()

,ordenID,productoID,UnitPrice,Quantity,NombreProducto,categoriaID,clienteID,fecha,NombreCategoria,TotalVenta,Mes
0,10248,11,14.0,12,Queso Cabrales,4,VINET,1996-07-04,Dairy Products,168.0,1996-07
1,10248,42,9.8,10,Singaporean Hokkien Fried Mee,5,VINET,1996-07-04,Grains/Cereals,98.0,1996-07
2,10248,72,34.8,5,Mozzarella di Giovanni,4,VINET,1996-07-04,Dairy Products,174.0,1996-07
3,10249,14,18.6,9,Tofu,7,TOMSP,1996-07-05,Produce,167.4,1996-07
4,10249,51,42.4,40,Manjimup Dried Apples,7,TOMSP,1996-07-05,Produce,1696.0,1996-07

In [4]:
# Ultimas 5 filas
df_ventas.tail()

,ordenID,productoID,UnitPrice,Quantity,NombreProducto,categoriaID,clienteID,fecha,NombreCategoria,TotalVenta,Mes
2150,11077,64,33.25,2,Wimmers gute Semmelknödel,5,RATTC,1998-05-06,Grains/Cereals,66.5,1998-05
2151,11077,66,17.00,1,Louisiana Hot Spiced Okra,2,RATTC,1998-05-06,Condiments,17.0,1998-05
2152,11077,73,15.00,2,Röd Kaviar,8,RATTC,1998-05-06,Seafood,30.0,1998-05
2153,11077,75,7.75,4,Rhönbräu Klosterbier,1,RATTC,1998-05-06,Beverages,31.0,1998-05
2154,11077,77,13.00,2,Original Frankfurter grüne Soße,2,RATTC,1998-05-06,Condiments,26.0,1998-05

In [5]:
# Información del dataset
f_info_general(df_ventas)

Información General

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ordenID          2155 non-null   int64
 1   productoID       2155 non-null   int64
 2   UnitPrice        2155 non-null   float64
 3   Quantity         2155 non-null   int64
 4   NombreProducto   2155 non-null   object
 5   categoriaID      2155 non-null   int64
 6   clienteID        2155 non-null   object
 7   fecha            2155 non-null   object
 8   NombreCategoria  2155 non-null   object
 9   TotalVenta       2155 non-null   float64
 10  Mes              2155 non-null   object
dtypes: float64(2), int64(4), object(5)
memory usage: 185.3+ KB

In [6]:
# Estadistica basica
f_estadistica(df_ventas)

Estadistica descriptiva

,ordenID,productoID,UnitPrice,Quantity,categoriaID,TotalVenta
count,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000
mean,10659.375870,40.793039,26.218520,23.812993,4.135499,628.519067
std,241.378032,22.159019,29.827418,19.022047,2.378567,1036.466980
min,10248.000000,1.000000,2.000000,1.000000,1.000000,4.800000
25%,10451.000000,22.000000,12.000000,10.000000,2.000000,154.000000
50%,10657.000000,41.000000,18.400000,20.000000,4.000000,360.000000
75%,10862.500000,60.000000,32.000000,30.000000,6.000000,722.250000
max,11077.000000,77.000000,263.500000,130.000000,8.000000,15810.000000

In [7]:
# Verificación de valores nulos
f_contar_nulos(df_ventas)

Recuento de valores NULL

ordenID            0
productoID         0
UnitPrice          0
Quantity           0
NombreProducto     0
categoriaID        0
clienteID          0
fecha              0
NombreCategoria    0
TotalVenta         0
Mes                0
dtype: int64

In [8]:
# Verificación de filas duplicadas
f_contar_duplicados(df_ventas)

Duplicados

np.int64(0)

In [9]:
# Columnas del dataset
f_columnas(df_ventas)

Columnas del archivo

Index(['ordenID', 'productoID', 'UnitPrice', 'Quantity', 'NombreProducto',
       'categoriaID', 'clienteID', 'fecha', 'NombreCategoria', 'TotalVenta',
       'Mes'],
      dtype='object')