In [63]:
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
df_ventas = pd.read_csv('../dataset/raw/ventas.csv')
df_ventas.head()

,ordenID,productoID,UnitPrice,Quantity,NombreProducto,categoriaID,clienteID,fecha,NombreCategoria,TotalVenta,Mes
0,10248,11,14.0,12,Queso Cabrales,4,VINET,1996-07-04,Dairy Products,168.0,1996-07
1,10248,42,9.8,10,Singaporean Hokkien Fried Mee,5,VINET,1996-07-04,Grains/Cereals,98.0,1996-07
2,10248,72,34.8,5,Mozzarella di Giovanni,4,VINET,1996-07-04,Dairy Products,174.0,1996-07
3,10249,14,18.6,9,Tofu,7,TOMSP,1996-07-05,Produce,167.4,1996-07
4,10249,51,42.4,40,Manjimup Dried Apples,7,TOMSP,1996-07-05,Produce,1696.0,1996-07

In [39]:
# Correccción de tipo de datos 
df_ventas['fecha'] = pd.to_datetime(df_ventas['fecha'])

df_ventas['Mes'] = df_ventas['fecha'].dt.to_period('M')

df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ordenID          2155 non-null   int64
 1   productoID       2155 non-null   int64
 2   UnitPrice        2155 non-null   float64
 3   Quantity         2155 non-null   int64
 4   NombreProducto   2155 non-null   object
 5   categoriaID      2155 non-null   int64
 6   clienteID        2155 non-null   object
 7   fecha            2155 non-null   datetime64[ns]
 8   NombreCategoria  2155 non-null   object
 9   TotalVenta       2155 non-null   float64
 10  Mes              2155 non-null   period[M]
 11  Year             2155 non-null   int32
 12  Mes_num          2155 non-null   int32
 13  CategoriaVentas  2153 non-null   category
 14  CategoriaVenta   2153 non-null   category
dtypes: category(2), datetime64[ns](1), float64(2), int32(2), int64(4), object(3), period[M](1)
memory usage: 206.6+ KB

In [70]:
# Creamos una columna CategoriaVentas
df_ventas["CategoriaVentas"] = pd.cut(df_ventas["TotalVenta"], 
                               bins=[0, 100, 1000, 5000, 16000], 
                               labels=["Baja", "Media", "Alta", "Muy Alta"])

df_ventas.head(60)

,ordenID,productoID,UnitPrice,Quantity,NombreProducto,categoriaID,clienteID,fecha,NombreCategoria,TotalVenta,Mes,CategoriaVentas
0,10248,11,14.0,12,Queso Cabrales,4,VINET,1996-07-04,Dairy Products,168.0,1996-07,Media
1,10248,42,9.8,10,Singaporean Hokkien Fried Mee,5,VINET,1996-07-04,Grains/Cereals,98.0,1996-07,Baja
2,10248,72,34.8,5,Mozzarella di Giovanni,4,VINET,1996-07-04,Dairy Products,174.0,1996-07,Media
3,10249,14,18.6,9,Tofu,7,TOMSP,1996-07-05,Produce,167.4,1996-07,Media
4,10249,51,42.4,40,Manjimup Dried Apples,7,TOMSP,1996-07-05,Produce,1696.0,1996-07,Alta
5,10250,41,7.7,10,Jack's New England Clam Chowder,8,HANAR,1996-07-08,Seafood,77.0,1996-07,Baja
6,10250,51,42.4,35,Manjimup Dried Apples,7,HANAR,1996-07-08,Produce,1484.0,1996-07,Alta
7,10250,65,16.8,15,Louisiana Fiery Hot Pepper Sauce,2,HANAR,1996-07-08,Condiments,252.0,1996-07,Media
8,10251,22,16.8,6,Gustaf's Knäckebröd,5,VICTE,1996-07-08,Grains/Cereals,100.8,1996-07,Media
9,10251,57,15.6,15,Ravioli Angelo,5,VICTE,1996-07-08,Grains/Cereals,234.0,1996-07,Media
10,10251,65,16.8,20,Louisiana Fiery Hot Pepper Sauce,2,VICTE,1996-07-08,Condiments,336.0,1996-07,Media
11,10252,20,64.8,40,Sir Rodney's Marmalade,3,SUPRD,1996-07-09,Confections,2592.0,1996-07,Alta
12,10252,33,2.0,25,Geitost,4,SUPRD,1996-07-09,Dairy Products,50.0,1996-07,Baja
13,10252,60,27.2,40,Camembert Pierrot,4,SUPRD,1996-07-09,Dairy Products,1088.0,1996-07,Alta
14,10253,31,10.0,20,Gorgonzola Telino,4,HANAR,1996-07-10,Dairy Products,200.0,1996-07,Media
15,10253,39,14.4,42,Chartreuse verte,1,HANAR,1996-07-10,Beverages,604.8,1996-07,Media
16,10253,49,16.0,40,Maxilaku,3,HANAR,1996-07-10,Confections,640.0,1996-07,Media
17,10254,24,3.6,15,Guaraná Fantástica,1,CHOPS,1996-07-11,Beverages,54.0,1996-07,Baja
18,10254,55,19.2,21,Pâté chinois,6,CHOPS,1996-07-11,Meat/Poultry,403.2,1996-07,Media
19,10254,74,8.0,21,Longlife Tofu,7,CHOPS,1996-07-11,Produce,168.0,1996-07,Media
20,10255,2,15.2,20,Chang,1,RICSU,1996-07-12,Beverages,304.0,1996-07,Media
21,10255,16,13.9,35,Pavlova,3,RICSU,1996-07-12,Confections,486.5,1996-07,Media
22,10255,36,15.2,25,Inlagd Sill,8,RICSU,1996-07-12,Seafood,380.0,1996-07,Media
23,10255,59,44.0,30,Raclette Courdavault,4,RICSU,1996-07-12,Dairy Products,1320.0,1996-07,Alta
24,10256,53,26.2,15,Perth Pasties,6,WELLI,1996-07-15,Meat/Poultry,393.0,1996-07,Media
25,10256,77,10.4,12,Original Frankfurter grüne Soße,2,WELLI,1996-07-15,Condiments,124.8,1996-07,Media
26,10257,27,35.1,25,Schoggi Schokolade,3,HILAA,1996-07-16,Confections,877.5,1996-07,Media
27,10257,39,14.4,6,Chartreuse verte,1,HILAA,1996-07-16,Beverages,86.4,1996-07,Baja
28,10257,77,10.4,15,Original Frankfurter grüne Soße,2,HILAA,1996-07-16,Condiments,156.0,1996-07,Media
29,10258,2,15.2,50,Chang,1,ERNSH,1996-07-17,Beverages,760.0,1996-07,Media
30,10258,5,17.0,65,Chef Anton's Gumbo Mix,2,ERNSH,1996-07-17,Condiments,1105.0,1996-07,Alta
31,10258,32,25.6,6,Mascarpone Fabioli,4,ERNSH,1996-07-17,Dairy Products,153.6,1996-07,Media
32,10259,21,8.0,10,Sir Rodney's Scones,3,CENTC,1996-07-18,Confections,80.0,1996-07,Baja
33,10259,37,20.8,1,Gravad lax,8,CENTC,1996-07-18,Seafood,20.8,1996-07,Baja
34,10260,41,7.7,16,Jack's New England Clam Chowder,8,OTTIK,1996-07-19,Seafood,123.2,1996-07,Media
35,10260,57,15.6,50,Ravioli Angelo,5,OTTIK,1996-07-19,Grains/Cereals,780.0,1996-07,Media
36,10260,62,39.4,15,Tarte au sucre,3,OTTIK,1996-07-19,Confections,591.0,1996-07,Media
37,10260,70,12.0,21,Outback Lager,1,OTTIK,1996-07-19,Beverages,252.0,1996-07,Media
38,10261,21,8.0,20,Sir Rodney's Scones,3,QUEDE,1996-07-19,Confections,160.0,1996-07,Media
39,10261,35,14.4,20,Steeleye Stout,1,QUEDE,1996-07-19,Beverages,288.0,1996-07,Media
40,10262,5,17.0,12,Chef Anton's Gumbo Mix,2,RATTC,1996-07-22,Condiments,204.0,1996-07,Media
41,10262,7,24.0,15,Uncle Bob's Organic Dried Pears,7,RATTC,1996-07-22,Produce,360.0,1996-07,Media
42,10262,56,30.4,2,Gnocchi di nonna Alice,5,RATTC,1996-07-22,Grains/Cereals,60.8,1996-07,Baja
43,10263,16,13.9,60,Pavlova,3,ERNSH,1996-07-23,Confections,834.0,1996-07,Media
44,10263,24,3.6,28,Guaraná Fantástica,1,ERNSH,1996-07-23,Beverages,100.8,1996-07,Media
45,10263,30,20.7,60,Nord-Ost Matjeshering,8,ERNSH,1996-07-23,Seafood,1242.0,1996-07,Alta
46,10263,74,8.0,36,Longlife Tofu,7,ERNSH,1996-07-23,Produce,288.0,1996-07,Media
47,10264,2,15.2,35,Chang,1,FOLKO,1996-07-24,Beverages,532.0,1996-07,Media
48,10264,41,7.7,25,Jack's New England Clam Chowder,8,FOLKO,1996-07-24,Seafood,192.5,1996-07,Media
49,10265,17,31.2,30,Alice Mutton,6,BLONP,1996-07-25,Meat/Poultry,936.0,1996-07,Media
50,10265,70,12.0,20,Outback Lager,1,BLONP,1996-07-25,Beverages,240.0,1996-07,Media
51,10266,12,30.4,12,Queso Manchego La Pastora,4,WARTH,1996-07-26,Dairy Products,364.8,1996-07,Media
52,10267,40,14.7,50,Boston Crab Meat,8,FRANK,1996-07-29,Seafood,735.0,1996-07,Media
53,10267,59,44.0,70,Raclette Courdavault,4,FRANK,1996-07-29,Dairy Products,3080.0,1996-07,Alta
54,10267,76,14.4,15,Lakkalikööri,1,FRANK,1996-07-29,Beverages,216.0,1996-07,Media
55,10268,29,99.0,10,Thüringer Rostbratwurst,6,GROSR,1996-07-30,Meat/Poultry,990.0,1996-07,Media
56,10268,72,27.8,4,Mozzarella di Giovanni,4,GROSR,1996-07-30,Dairy Products,111.2,1996-07,Media
57,10269,33,2.0,60,Geitost,4,WHITC,1996-07-31,Dairy Products,120.0,1996-07,Media
58,10269,72,27.8,20,Mozzarella di Giovanni,4,WHITC,1996-07-31,Dairy Products,556.0,1996-07,Media
59,10270,36,15.2,30,Inlagd Sill,8,WARTH,1996-08-01,Seafood,456.0,1996-08,Media

In [52]:
# Validación final
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ordenID          2155 non-null   int64
 1   productoID       2155 non-null   int64
 2   UnitPrice        2155 non-null   float64
 3   Quantity         2155 non-null   int64
 4   NombreProducto   2155 non-null   object
 5   categoriaID      2155 non-null   int64
 6   clienteID        2155 non-null   object
 7   fecha            2155 non-null   datetime64[ns]
 8   NombreCategoria  2155 non-null   object
 9   TotalVenta       2155 non-null   float64
 10  Mes              2155 non-null   period[M]
 11  CategoriaVentas  2153 non-null   category
dtypes: category(1), datetime64[ns](1), float64(2), int64(4), object(3), period[M](1)
memory usage: 187.6+ KB

In [56]:
df_ventas[['UnitPrice', 'Quantity', 'TotalVenta']].describe().round(2)

       UnitPrice  Quantity  TotalVenta
count    2155.00   2155.00     2155.00
mean       26.22     23.81      628.52
std        29.83     19.02     1036.47
min         2.00      1.00        4.80
25%        12.00     10.00      154.00
50%        18.40     20.00      360.00
75%        32.00     30.00      722.25
max       263.50    130.00    15810.00

In [60]:
# Revisamos nuevamente valores null
df_ventas.isnull().sum()

ordenID            0
productoID         0
UnitPrice          0
Quantity           0
NombreProducto     0
categoriaID        0
clienteID          0
fecha              0
NombreCategoria    0
TotalVenta         0
Mes                0
CategoriaVentas    0
dtype: int64

In [72]:
# Guardamos el Dataset limpio y transformado
df_ventas.to_csv('../dataset/procesado/ventas_limpio.csv', index = False)