In [1]:
import pandas as pd

In [2]:
df_ventas = pd.read_csv('../dataset/procesado/ventas_limpio.csv')

df_ventas.head()

,ordenID,productoID,UnitPrice,Quantity,NombreProducto,categoriaID,clienteID,fecha,NombreCategoria,TotalVenta,Mes,CategoriaVentas
0,10248,11,14.0,12,Queso Cabrales,4,VINET,1996-07-04,Dairy Products,168.0,1996-07,Media
1,10248,42,9.8,10,Singaporean Hokkien Fried Mee,5,VINET,1996-07-04,Grains/Cereals,98.0,1996-07,Baja
2,10248,72,34.8,5,Mozzarella di Giovanni,4,VINET,1996-07-04,Dairy Products,174.0,1996-07,Media
3,10249,14,18.6,9,Tofu,7,TOMSP,1996-07-05,Produce,167.4,1996-07,Media
4,10249,51,42.4,40,Manjimup Dried Apples,7,TOMSP,1996-07-05,Produce,1696.0,1996-07,Alta

In [18]:
# KPI principal (Ventas totales)
ventas_totales = df_ventas['TotalVenta'].sum()

print(f'Venta total {ventas_totales:,.2f}')

Venta total 1,354,458.59

In [20]:
# Top 10 ventas por productos
top_ventas_productos = df_ventas.groupby('NombreProducto', as_index = False).agg(
    TotalVenta = ('TotalVenta', 'sum')).sort_values('TotalVenta', ascending = False).head(10)

top_ventas_productos

             NombreProducto  TotalVenta
11            Côte de Blaye    149984.2
68  Thüringer Rostbratwurst     87736.4
51     Raclette Courdavault     76296.0
3         Camembert Pierrot     50286.0
66           Tarte au sucre     49827.9
17   Gnocchi di nonna Alice     45121.2
36    Manjimup Dried Apples     44742.6
0              Alice Mutton     35482.2
4          Carnarvon Tigers     31987.5
56        Rössle Sauerkraut     26865.6

In [21]:
# Top 5 clientes que más compra
top_cliente = df_ventas.groupby('clienteID', as_index = False).agg(
    TotalVenta = ('TotalVenta', 'sum')).sort_values('TotalVenta', ascending = False).head(5)

top_cliente

   clienteID  TotalVenta
60     QUICK   117483.39
68     SAVEA   115673.39
19     ERNSH   113236.68
35     HUNGO    57317.39
62     RATTC    52245.90

In [23]:
# Venta por mes
venta_mes = df_ventas.groupby('Mes', as_index = False).agg(
    TotalVenta = ('TotalVenta', 'sum')
)

venta_mes

        Mes  TotalVenta
0   1996-07    30192.10
1   1996-08    26609.40
2   1996-09    27636.00
3   1996-10    41203.60
4   1996-11    49704.00
5   1996-12    50953.40
6   1997-01    66692.80
7   1997-02    41207.20
8   1997-03    39979.90
9   1997-04    55699.39
10  1997-05    56823.70
11  1997-06    39088.00
12  1997-07    55464.93
13  1997-08    49981.69
14  1997-09    59733.02
15  1997-10    70328.50
16  1997-11    45913.36
17  1997-12    77476.26
18  1998-01   100854.72
19  1998-02   104561.95
20  1998-03   109825.45
21  1998-04   134630.56
22  1998-05    19898.66

In [27]:
# Top 10 productos más vendidos
productos_cantidad_venta = df_ventas.groupby('NombreProducto', as_index = False).agg(
    Quantity = ('Quantity', 'sum')).sort_values('Quantity', ascending = False).head(10)

productos_cantidad_venta

            NombreProducto  Quantity
3        Camembert Pierrot      1577
51    Raclette Courdavault      1496
18       Gorgonzola Telino      1397
17  Gnocchi di nonna Alice      1263
46                 Pavlova      1158
53    Rhönbräu Klosterbier      1155
21      Guaraná Fantástica      1125
2         Boston Crab Meat      1103
66          Tarte au sucre      1083
14             Flotemysost      1057

In [32]:
# Ingreso promedio por venta
promedio_por_venta = df_ventas['TotalVenta'].mean().round(2)

print(f'Ingreso promedio es: {promedio_por_venta}')

Ingreso promedio es: 628.52